#! /bin/bash
action=$1
case $action in
    dev)
        echo "[+] Install pigger to local ..."
        packr
        go install
        packr clean
        echo "[+] Install pigmgr to local ..."
        cd pigmgr
        go install
        echo "All is done!"
        ;;
    pigger)
        read -p "Version number for pigger: " piggerver
        echo "${piggerver}" > LATEST
        echo "[+] Install pigger to local ..."
        packr
        go install
        echo "[+] Cross compile pigger for linux, windows and mac ..."
        gox -output="release/pigger_{{.OS}}_{{.Arch}}" -os="linux windows darwin" -arch="amd64 386"
        packr clean
        echo "Compile pigger is done!"
        ;;
    pigmgr)
        cd pigmgr
        read -p "Version number for pigmgr: " pigmgrver
        echo "${pigmgrver}" > LATEST
        echo "[+] Install pigmgr to local ..."
        go install
        echo "[+] Cross compile pigmgr for linux, windows and mac ..."
        gox -output="../release/pigmgr_{{.OS}}_{{.Arch}}" -os="linux windows darwin" -arch="amd64 386"
        echo "Compile pigmgr is done!"
        ;;
    *)
        echo "Usage: $0 {dev|pigger|pigmgr}"
        exit 1
esac
