#! /bin/bash
action=$1

function setversion() {
    info="$1"
    codefile=$2
    read -p "$info" version
    echo "${version}" > LATEST
    sed -i "/const VERSION/c\const VERSION = \"$version\"" "$codefile"
}

function compile_pigger() {
    setversion "Version number for pigger: " main.go
    echo "[+] Install pigger to local ..."
    packr
    go install
    echo "[+] Cross compile pigger for linux, windows and mac ..."
    gox -output="release/pigger_{{.OS}}_{{.Arch}}" -os="linux windows darwin" -arch="amd64 386"
    packr clean
    echo "Compile pigger is done!"
}

function compile_pigmgr() {
    cd pigmgr
    setversion "Version number for pigmgr: " main.go
    echo "[+] Install pigmgr to local ..."
    go install
    echo "[+] Cross compile pigmgr for linux, windows and mac ..."
    gox -output="../release/pigmgr_{{.OS}}_{{.Arch}}" -os="linux windows darwin" -arch="amd64 386"
    echo "Compile pigmgr is done!"
}

case $action in
    dev)
        echo "[+] Install pigger to local ..."
        packr
        go install
        packr clean
        echo "[+] Install pigmgr to local ..."
        cd pigmgr
        go install
        echo "All is done!"
        ;;
    pigger)
        compile_pigger
        ;;
    pigmgr)
        compile_pigmgr
        ;;
    all)
        compile_pigger
        compile_pigmgr
        ;;
    *)
        echo "Usage: $0 {dev|pigger|pigmgr|all}"
        exit 1
esac
